name: hello-world
on:
  push:
jobs:
  my-job:
    runs-on: action-runner-image
    steps:
      - name: my-step
        run: echo "Hello Worldlast!"
      - name: second-step
        run: echo "Hello Worldlast2!"
